# copied from Omisharp https://github.com/OmniSharp/omnisharp-roslyn/blob/master/.travis.yml
language: csharp
sudo: false
install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh
  | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
before_script:
  - chmod +x build.sh
script:
- ". ./build.sh"
#deploy:
#  provider: releases
#  api_key:
#    secure: XXX
#  file: 'Veggerby.Units.tar.gz'
#  skip_cleanup: true
#  on:
#    repo: Veggerby/Veggerby.Units
#    tags: true
#    all_branches: true