# copied from Omisharp https://github.com/OmniSharp/omnisharp-roslyn/blob/master/.travis.yml
language: csharp
sudo: false
mono: none
dotnet: 2.2.301
script:
- dotnet restore ./test/Veggerby.Units.Tests
- dotnet test ./test/Veggerby.Units.Tests
#deploy:
#  provider: releases
#  api_key:
#    secure: XXX
#  file: 'Veggerby.Units.tar.gz'
#  skip_cleanup: true
#  on:
#    repo: Veggerby/Veggerby.Units
#    tags: true
#    all_branches: true