name: ci-repeatability
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/ci-repeatability.yml'
      - 'bench/**'
      - 'scripts/**'

jobs:
  repeatability-and-perf:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: First test run
        run: dotnet test test/Veggerby.Units.Tests -c Release --nologo --verbosity minimal
      - name: Second test run
        run: dotnet test test/Veggerby.Units.Tests -c Release --nologo --verbosity minimal
      - name: Build benchmarks
        run: dotnet build bench/Veggerby.Units.Benchmarks -c Release
      - name: Run benchmarks
        run: |
          dotnet run --project bench/Veggerby.Units.Benchmarks -c Release -- --exporters markdown --allCategories equality
      - name: Extract benchmark summary
        run: |
          dotnet tool install -g dotnet-script
          export PATH="$HOME/.dotnet/tools:$PATH"
          REPORT=$(ls BenchmarkDotNet.Artifacts/results/*-report-github.md | head -n 1)
          echo "Using benchmark report: $REPORT"
          dotnet script scripts/extract-benchmark-summary.csx -- "$REPORT" bench/Veggerby.Units.Benchmarks/current-benchmark-summary.json
          cat bench/Veggerby.Units.Benchmarks/current-benchmark-summary.json
      - name: Compare against baseline (shell)
        run: |
          chmod +x scripts/compare-benchmarks.sh
          ./scripts/compare-benchmarks.sh bench/Veggerby.Units.Benchmarks/Baseline/equality-baseline.json bench/Veggerby.Units.Benchmarks/current-benchmark-summary.json 1.0
